import { environment } from '../../environments/environment';
import { DomSanitizer } from '@angular/platform-browser';


/**
 * Export contants from this file
 */

export const emailRegexp = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export const numberOnlyRegExp = /^\d+$/;

export const allowedCategories = ["Food", "Shop", "Accomodation"];

export const contactRegExp = /^(009665|9665|\+9665|05|5)(5|0|3|6|4|9|1|8|7)([0-9]{7})$/;

export const priceValue = /^(?:[1-9][0-9]{0,4}(?:\.\d{1,2})?|999999|99999.00)$/;

export const getImageUrl = (imageId) => {
    let url = imageId ? `url(${environment.base_url}/files/${imageId}?api_key=${environment.api_key})` : 'url(../../../assets/images/img_placeholder.svg)';
    return { 'background-image': url }
}
export const imageUrl = (imageId) => {
    let imgUrl = imageId ? environment.base_url + "/files/" + imageId + "?api_key=" + environment.api_key : '../../../assets/images/na.jpg'
    return imgUrl;
}

export const userType = "Manager"

export const youtubeUrlRegexp = /^(?:https?:\/\/)?(?:m\.|www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/;

/**
 * Pass the youtube video id and the DomSanitizer object to view the embed url for listing videos from youtube.
 * @param id 
 * @param sanitizer 
 */
export const getVideoURL = (id, sanitizer: DomSanitizer) => {
    let dangerousVideoUrl = 'https://www.youtube.com/embed/' + id;
    return sanitizer.bypassSecurityTrustResourceUrl(dangerousVideoUrl);
}

// used for arabic text to view in ui
export const arabicText = {
    "ACCOMODATION": "ACCOMODATION",
    "ACCOMODATION_TYPE": "ACCOMODATION_TYPE",
    "ACTIVE": "ACTIVE",
    "ADD": "ADD",
    "CLEAR": "CLEAR",
    "ADDRESS": "ADDRESS",
    "ALL": "ALL",
    "AVAILABLE": "AVAILABLE",
    "Business_updated": "Business_updated",
    "Failed_to_update_business": "Failed_to_update_business",
    "Cover_Image_Required": "Cover_Image_Required",
    "Cover_Image_Square_Required": "Cover_Image_Square_Required",
    "BLOCKED": "BLOCKED",
    "BUSINESS": "BUSINESS",
    "BUSINESS_DETAILS": "BUSINESS_DETAILS ",
    "BUSINESS_FOOD": "BUSINESS_FOOD ",
    "BUSINESS_FOOD_DETAILS": "BUSINESS_FOOD_DETAILS  ",
    "CANCEL": "CANCEL",
    "CARPET_AREA": "CARPET_AREA ",
    "CATEGORIES": "CATEGORIES",
    "CHEFS": "CHEFS",
    "CHEF_NAME": "CHEF_NAME ",
    "Panoramic_images": "Panoramic_images ",
    "COVER_IMAGE": "COVER_IMAGE",
    "COVER_IMAGE_SQUARE": "COVER_IMAGE_SQUARE",
    "DAY": "DAY",
    "DAY_WISE_TIMING":"DAY_WISE_TIMING",
    "DESCRIPTION": "DESCRIPTION",
    "DETAILS": "DETAILS",
    "EDIT": "EDIT",
    "EMAIL": "EMAIL",
    "END_TIME": "END_TIME",
    "FOOD": "FOOD",
    "FORGOT_PASSWORD": "FORGOT_PASSWORD",
    "FORGOT_PASSWORD_BUTTON": "FORGOT_PASSWORD_BUTTON",
    "IMAGES": "IMAGES",
    "LOGIN":"LOGIN",
    "LOGOUT": "LOGOUT",
    "MENU": "MENU",
    "CATEGORY": "CATEGORY",
    "Old_Password": "Old_Password",
    "MENU_CATEGORY": "MENU_CATEGORY",
    "MOBILE": "MOBILE",
    "Manage_Bussiness_Shop_Details": "Manage_Bussiness_Shop_Details",
    "NAME": "NAME",
    "New_Password": "New_Password",
    "Confirm_Password": "Confirm_Password",
    "Reset_Password": "Reset_Password",
    "NOT_AVAILABLE": "NOT_AVAILABLE",
    "New_Business": "New_Business",
    "No_Records": "No_Records",
    "PANORAMIC_IMAGE": "PANORAMIC_IMAGE",
    "PASSWORD": "PASSWORD",
    "PRICE": "PRICE",
    "RENTAL_PRICE": "RENTAL_PRICE",
    "SAVE": "SAVE",
    "SEARCH": "SEARCH",
    "SHOP": "SHOP",
    "Please_upload_a_valid_url_for_youtube": "Please_upload_a_valid_url_for_youtube",
    "Conection_problem": "Conection_problem",
    "Image_updated_Successfully": "Image_updated_Successfully",
    "Category_updated_successfully": "Category_updated_successfully",
    "SIDE_MENU": {
        "DASHBOARD": "DASHBOARD",
        "FEATURED_BUSINESS":"FEATURED_BUSINESS",
        "FEATURED_FEEDBACK": "FEATURED_FEEDBACK",
        "FEATURED_IMAGE": "FEATURED_IMAGE",
        "FEATURED_OFFER": "FEATURED_OFFER",
        "FEATURED_VIDEO": "FEATURED_VIDEO",
        "MANAGE_BUSINESS": "MANAGE_BUSINESS",
        "MANAGE_CHANGE_PASSWORD": "MANAGE_CHANGE_PASSWORD",
        "MANAGE_CONTACT": "MANAGE_CONTACT",
        "MANAGE_FEEDBACK": "MANAGE_FEEDBACK",
        "MANAGE_ACCOUNT": "MANAGE_ACCOUNT",
        "MANAGE_QUOTATION": "MANAGE_QUOTATION",
        "MANAGE_OFFER": "MANAGE_OFFER",
        "MANAGE_USERS": "MANAGE_USERS",
        "MANAGE_CATEGORY": "MANAGE_CATEGORY"
    },
    "SPECIAL_MENUS": "SPECIAL_MENUS",
    "START_TIME": "START_TIME",
    "STATUS": "STATUS",
    "Search_Address": "Search_Address",
    "TITLE": "TITLE",
    "TITLE_ACCOMODATION_DETAILs": "TITLE_ACCOMODATION_DETAILs",
    "VIDEOS": "VIDEOS",
    "errors": {
        "ADDRESS_REQUIRED":"ADDRESS_REQUIRED",
        "CATEGORIES_REQUIRED": "CATEGORIES_REQUIRED",
        "EMAIL_REQUIRED": "EMAIL_REQUIRED",
        "Description_is_required": "Description_is_required",
        "Title_is_required": "Title_is_required",
        "EMAIL_NOT_VALID": "EMAIL_NOT_VALID",
        "PASSWORD_REQUIRED":"PASSWORD_REQUIRED",
        "Failed_To_Create_Business": "Failed_To_Create_Business",
        "Failed_To_Update_Business": "Failed_To_Update_Business",
        "IMAGE_REQUIRED": "IMAGE_REQUIRED",
        "MOBILE_REQUIRED": "MOBILE_REQUIRED",
        "NAME_REQUIRED": "NAME_REQUIRED",
        "NEW_PASSWORD_REQUIRED": "NEW_PASSWORD_REQUIRED",
        "PASSWORD_SHOULD_ATLEAST_CHARACTER": "PASSWORD_SHOULD_ATLEAST_CHARACTER",
        "Confirm_Password_is_required": "Confirm_Password_is_required",
        "New_Password_and_confirm_password_match": "New_Password_and_confirm_password_match",
        "Old_Password_is_required": "Old_Password_is_required",
        "Old_Password_should_have_at_least_4_characters_and_atmost_15_characters":"Old_Password_should_have_at_least_4_characters_and_atmost_15_characters",
        "New_Password_should_have_at_least_4_characters_and_atmost_15_characters": "New_Password_should_have_at_least_4_characters_and_atmost_15_characters",
        "Old_password_and_new_password_cannot_be_same": "Old_password_and_new_password_cannot_be_same",
        "Video_failed_to_Upload": "فشل تحميل الفيديو",


        "Chef_Image_Required": "Chef Image is Required",
        "Menu_Category_Required": "Menu Category is required",
    },
    "success": {
        "Business_Accomodation_Updated_Successfully": "Business_Accomodation_Updated_Successfully",
        "Business_Food_Updated_Successfully": "Business_Food_Updated_Successfully",
        "Business_Shop_Updated_Successfully": "Business_Shop_Updated_Successfully",
        "Business_created": "Business_created",
        "Business_updated": "Business_updated",
        "Category_Updated_Successfully": "Category_Updated_Successfully",
        "Chef_Updated_Successfully": "Chef_Updated_Successfully",
        "Image_Deleted_Successfully": "Image_Deleted_Successfully",
        "Image_Updated_Successfully": "Image_Updated_Successfully",
        "Image_Uploaded_Successfully": "Image_Uploaded_Successfully",
        "Shop_Item_Updated_Successfully": "Shop_Item_Updated_Successfully",
        "Video_Deleted_Successfully": "Video_Deleted_Successfully",
        "Video_Updated_Successfully": "Video_Updated_Successfully",
        "Video_Uploaded_Successfully": "Video_Uploaded_Successfully",


        "Chef_Added_Successfully": "Chef Added successfully"
    },


    "categoryType": {
        "Suggestion": "Suggestion",
        "Query": "Query",
        "Complaint": "Complaint",
        "Others": "Others"
    },
    "Listing": "Listing",
    "Accomodation_Type": "Accomodation Type",
    "Maximim_Limit_Reached_Upload_Image": "Maximum limit reached for uploading imgaes.If you want to add then remove first and then add it.",
    "Click_Upload_Image": "Click here to upload new image",
    "UPLOAD": "UPLOAD",
    "Show_On_Details": "Show On Details",
    "Maximim_Limit_Reached_Upload_Video": "Maximum limit reached for uploading videos.If you want to add then remove first and then add it.",
    "Add_Menu": "Add Menu",
    "SAR": "(SAR)",
    "Conection_Problem": "Conection problem",
    "Account_Detail": "Account Detail",
    "Change_Password": "Change Password",
    "Full_Name": "Full Name",
    "Mobile_Invalid": "Mobile number is not valid",
    "Account_updated_successfully": "Account details updated successfully",
    "Chef_Image": "Chef Image",
    "Edit_Chef": "Edit Chef",
    "Unavailable": "Unavailable",
    "Heading": "Heading",
    "Special": "Special",
    "Menu_Updated_successfully": "Menu updated successfully",
    "Quantity_Price": "Quantity Price",
    "Quantity_Price_Required": "Quantity Price is required",
    "Quantity_Price_between": "Quantity price must lies between (1-99999)",
    "Add_Special_Price": "Add Special Price",
    "Menu_Added_successfully": "Menu added successfully",
    "Add_Banquet_Menu": "Add Banquet Menu",
    "Edit_Banquet_Menu": "Edit Banquet Menu",
    "Change_Password_Successfuly": "Change password successfuly",
    "Confirm": "Confirm",
    "AreYouSureRemove": "Are you sure you want to remove?",
    "Close": "Close",
    "Full_Name_Required": "Full Name is required",
    "Email_Required": "Email is required",
    "Email_Not_Valid": "Email is not valid",
    "Message": "Message",
    "Message_Required": "Message is required",
    "Select_Category": "Select Category",
    "Category_Required": "Category is required",
    "Contact_Us": "Contact Us",
    "Send": "Send",
    "Contact_Created_Successfully": "Contact us created Successfully",
    "Tawtini_Catering": "Tawtini Catering",
    "Manage_Feedback": "Manage Feedback",
    "Pending": "Pending",
    "Inactive": "Inactive",
    "Category": "category",
    "User_Name": "User Name",
    "Date_Of_arrival": "Date of arrival",
    "No_Records_Found": "No Records found",
    "Feedback": "Feedback",
    "Updated": "Updated",
    "Heading_Required": "Heading is required",
    "Price_Required": "Price is required",
    "Price_Must_Between": "Price must lies between (1-99999)",
    "Remove": "Remove",
    "Edit_Menu": "Edit Menu",
    "Your_Reset_Send": "Your Reset password link is succesfully send",
    "Visits": "Visits",
    "User_Business_Favourite": "User with Business as favourite",
    "Offers": "Offers",
    "Feedbacks": "Feedbacks",
    "Total_Quotation_Request": "Total Quotation Request",
    "Sub_Categories": "Sub Categories",
    "Banquets": "Banquets",
    "Bunglows": "Bunglows",
    "Rooms": "Rooms",
    "Villas": "Villas",
    "Rental_Price": "Rental Price",
    "Rental_Price_Required": "Rental Price is required",
    "Rectail_Price_Lies_Between": "Rental Price must lies between (1-99999)",
    "Carpet_Area_Required": "Carpet Area is required",
    "Carpet_Area_Lies_Between": "Carpet Area must lies between (1-99999)",
    "Accomodation_Type_Required": "Accomodation Type is required",
    "Paranomic_Image": "Paranomic Image",
    "Add_More_Paranomic_Image": "Add More Paranomic Image",
    "Add_Image": "Add Image",
    "Image": "Image",
    "Add_Video": "Add Video",
    "Enter_YouTube_Link": "Enter YouTube Link",
    "Business_Food_updated_successfully": "Business Food updated successfully",
    "Business_Accomodation_updated_successfully": "Business Accomodation updated successfully",
    "Business_Shop_updated_successfully": "Business Shop updated successfully",
    "Business_Updated": "Business  updated",
    "Manage_Bussiness_Accomodations_Details": "Manage Bussiness Accomodations Details",
    "Bussiness_Accomodations_Updated_Successfully": "Bussiness Accomodations Updated Successfully",
    "Bussiness_Accomodations_Created_Successfully": "Bussiness Accomodations Created Successfully",
    "Paranomic_Required_Or_Remove": "Paranomic is Required or you can remove that image",
    "Add_Chef": "Add Chef",
    "Start_Time": "وقت البدء",
    "End_Time": "وقت النهاية",
    "Manage_Chef": "Manage Chef",
    "Menu": "Menu",
    "Enter_Title": "Enter Title",
    "Add_Bussiness_Food": "Add Bussiness Food",
    "Bussiness_Food_Added_Successfully": "Bussiness Food Added Successfully",
    "Bussiness_Food_Updated_Successfully": "Bussiness Food Updated Successfully",
    "Edit_Business_Food": "Edit Business Food",
    "Start_time_must_be_less_than_end_time": "Start time must be less than end time",
    "End_time_of": "End time of",
    "Start_time_of": "Start time of",
    "Required_otherWise_don_enter_remove_start_date": "Required otherWise don't enter remove start date",
    "Required_otherWise_don_enter_remove_end_date": "Required otherWise don't enter remove end date",
    "Add_Shop_Item": "Add Shop Item",
    "Manage_Shop_Items": "Manage Shop Items",
    "Edit_Bussiness_Shop": "Edit Bussiness Shop",
    "Add_Bussiness_Shop": "Add Bussiness Shop",
    "Business_Shop_created_successfully": "Business Shop created successfully",
    "Apply_To_All": "Apply To All",
    "Business_Shop_items_updated_successfully": "Business Shop items updated successfully",
    "Business_Shop_items_created_successfully": "Business_Shop_items_created_successfully",
    "Edit_Bussiness_Shop_Items": "Edit Bussiness Shop Items",
    "Add_Bussiness_Shop_Items": "Add Bussiness Shop Items",
    "Offers_Updated_Successfully": "Offers Updated Successfully",
    "Offers_Added_Successfully": "Offers Added Successfully",
    "Select_category": "Select category",
    "Category_required": "Category is required",
    "Valid_From": "Valid From",
    "Valid_From_is_required": "Valid From is required",
    "Valid_From_is_not_valid": "Valid From is not valid",
    "Select_offer_type": "Select offer type",
    "Offer_Type_is_required": "Offer Type is required",
    "Valid_Till": "Valid Till",
    "Valid_Till_is_required": " Valid Till is required",
    "Valid_Till_is_not_valid": "Valid Till is not valid",
    "Offer_Value": "Offer Value",
    "Offer_Value_is_not_valid": "Offer Value is not valid",
    "Offers_updated_sucessfully": "Offers updated sucessfully",
    "Offer_Type": "Offer Type",
    "offer_Value": "offer Value",
    "Expired": "Expired",
    "PERSONAL_DETAILS": "Personal Details",


    "Manage_Bussiness_Food_Details": "Manage Bussiness Food Details",
    "Read": "Read",
    "UnRead": "UnRead",
    "Customer_Details": "Customer Details",
    "Read_Unread": "Read/Unread",
    "Pending_Active_Inactive": "Pending / Active / Inactive",
    "Banquet": "Banquet",
    "Bunglow": "Bunglow",
    "Room": "Room",
    "Villa": "Villa",
    "Banquets_Menu":"Banquets Menu",
    "Breakfast":"Breakfast",
    "Lunch":"Lunch",
    "Dinner":"Dinner",
    "Starters":"Starters",
    "General_Info":"General Info",
}

export const constantCategories = {
    'FOOD': 'Food',
    'SHOP': 'Shop',
    'ACCOMODATION': 'Accomodation',
    'accomodationCategories': {
        'ROOMS': 'Rooms',
        'BUNGLOWS': 'Bunglows',
        'VILLAS': 'Villas',
        'BANQUETS': 'Banquets'
    },
    'menuCategory': {
        'Breakfast': 'Breakfast',
        'Lunch': 'Lunch',
        'Dinner': 'Dinner',
        'Starter': 'Starter'
    }
}